#!/usr/bin/env python3
"""
LandWise Obsidian Vault Sync
=============================
Reads live data from JARVIS bridge JSON stores and writes formatted
Markdown summaries into the Obsidian vault.

Usage:
    python3 sync_vault.py           # run once
    python3 sync_vault.py --once    # explicit one-shot (same as above)
    python3 sync_vault.py --watch   # loop every 5 minutes (daemon mode)

All paths resolve relative to ~/Desktop/LandWise/ so they work on any Mac.
"""

import os
import sys
import json
import time
import shutil
from datetime import datetime, timezone

# ── PATH SETUP ───────────────────────────────────────────────────────────────

BASE         = os.path.expanduser("~/Desktop/LandWise")
BRIDGE_DIR   = os.path.join(BASE, "Jarvis", "bridge")
VAULT_DIR    = os.path.join(BASE, "Obsidian-Vault")
BRIEFINGS    = os.path.join(BASE, "briefings")

CRM_FILE     = os.path.join(BRIDGE_DIR, "crm_store.json")
TASK_LOG     = os.path.join(BRIDGE_DIR, "task_log.json")
ACTIONS_FILE = os.path.join(BRIDGE_DIR, "pending_actions.json")

VAULT_MEMORY = os.path.join(VAULT_DIR, "memory")
VAULT_LOGS   = os.path.join(VAULT_DIR, "logs")

INTERVAL_SECONDS = 300  # 5 minutes

# ── HELPERS ───────────────────────────────────────────────────────────────────

def _read_json(path: str, default):
    try:
        with open(path, "r") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return default

def _write(path: str, content: str):
    """Write content to a file, creating parent dirs as needed."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)

def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

def _today() -> str:
    return datetime.now().strftime("%Y-%m-%d")

# ── SYNC FUNCTIONS ────────────────────────────────────────────────────────────

def sync_crm_snapshot():
    """crm_store.json → memory/crm-snapshot.md"""
    records = _read_json(CRM_FILE, [])
    ts = _now()

    lines = [
        "# CRM Snapshot",
        f"*Auto-generated by sync_vault.py — {ts}*",
        f"*Total leads: {len(records)}*",
        "",
    ]

    if not records:
        lines += [
            "> Pipeline is clear — no leads yet.",
            "",
            "---",
            "*Waiting for first enquiry.*",
        ]
    else:
        # Group by status
        by_status: dict = {}
        for r in records:
            s = r.get("status", "unknown")
            by_status.setdefault(s, []).append(r)

        for status, leads in sorted(by_status.items()):
            lines.append(f"## {status.replace('_', ' ').title()} ({len(leads)})")
            lines.append("")
            for r in leads:
                name  = r.get("name", "Unknown")
                score = r.get("score", "—")
                email = r.get("email", "")
                phone = r.get("phone", "")
                notes = r.get("notes", "")
                created = r.get("created_at", "")[:10]
                updated = r.get("updated_at", "")[:10]

                lines.append(f"### {name}")
                lines.append(f"- **Score:** {score}")
                if email:
                    lines.append(f"- **Email:** {email}")
                if phone:
                    lines.append(f"- **Phone:** {phone}")
                if notes:
                    lines.append(f"- **Notes:** {notes}")
                lines.append(f"- **Created:** {created}  |  **Updated:** {updated}")
                lines.append("")

    _write(os.path.join(VAULT_MEMORY, "crm-snapshot.md"), "\n".join(lines))
    print(f"[{_now()}] ✓ crm-snapshot.md written ({len(records)} leads)")


def sync_activity_log():
    """task_log.json → logs/jarvis-activity.md (appends recent entries)"""
    entries = _read_json(TASK_LOG, [])
    if not entries:
        return

    # Take last 20 entries
    recent = entries[-20:]
    ts = _now()

    lines = [
        "",
        f"## Sync batch — {ts}",
        "",
    ]
    for e in recent:
        stamp   = e.get("timestamp", "")[:19].replace("T", " ")
        agent   = e.get("agent_used", "jarvis")
        command = (e.get("command") or "")[:120]
        status  = e.get("status", "")
        lines.append(f"- `{stamp}` **[{agent}]** {status} — {command}")

    lines.append("")

    log_path = os.path.join(VAULT_LOGS, "jarvis-activity.md")
    os.makedirs(os.path.dirname(log_path), exist_ok=True)

    # Append mode — only write if file exists, otherwise create with header
    if os.path.exists(log_path):
        with open(log_path, "a") as f:
            f.write("\n".join(lines))
    else:
        header = [
            "# JARVIS Activity Log",
            "*Auto-generated by sync_vault.py*",
            "",
        ]
        with open(log_path, "w") as f:
            f.write("\n".join(header + lines))

    print(f"[{_now()}] ✓ jarvis-activity.md updated ({len(recent)} entries appended)")


def sync_pending_actions():
    """pending_actions.json → memory/pending-actions.md"""
    actions = _read_json(ACTIONS_FILE, [])
    ts = _now()

    pending  = [a for a in actions if a.get("status") == "pending"]
    executed = [a for a in actions if a.get("status") in ("executed", "approved")]
    rejected = [a for a in actions if a.get("status") == "rejected"]

    lines = [
        "# Pending Actions",
        f"*Auto-generated by sync_vault.py — {ts}*",
        f"*Total: {len(actions)} | Pending: {len(pending)} | Executed: {len(executed)} | Rejected: {len(rejected)}*",
        "",
    ]

    if pending:
        lines.append("## ⏳ Awaiting Approval")
        lines.append("")
        for a in pending:
            short_id    = a.get("short_id") or a.get("id", "")[:8]
            action_type = a.get("action_type", "unknown")
            channel     = a.get("channel", "")
            content     = (a.get("content") or "")[:200]
            queued_at   = a.get("queued_at", "")[:19].replace("T", " ")
            lines += [
                f"### `{short_id}` — {action_type}",
                f"- **Channel:** {channel}",
                f"- **Queued:** {queued_at}",
                f"- **Preview:** {content}{'...' if len(a.get('content',''))>200 else ''}",
                "",
            ]
    else:
        lines += ["## ✅ No pending actions", ""]

    if executed:
        lines.append("## ✅ Recently Executed")
        lines.append("")
        for a in executed[-5:]:
            short_id  = a.get("short_id") or a.get("id", "")[:8]
            atype     = a.get("action_type", "")
            acted_at  = a.get("acted_at", "")[:19].replace("T", " ")
            lines.append(f"- `{short_id}` {atype} — {acted_at}")
        lines.append("")

    _write(os.path.join(VAULT_MEMORY, "pending-actions.md"), "\n".join(lines))
    print(f"[{_now()}] ✓ pending-actions.md written ({len(pending)} pending)")


def sync_daily_brief():
    """briefings/YYYY-MM-DD.md → memory/daily-brief.md"""
    today = _today()
    src   = os.path.join(BRIEFINGS, f"{today}.md")
    dst   = os.path.join(VAULT_MEMORY, "daily-brief.md")

    if os.path.exists(src):
        shutil.copy2(src, dst)
        print(f"[{_now()}] ✓ daily-brief.md copied from briefings/{today}.md")
    else:
        # Write a placeholder if no brief exists yet
        placeholder = (
            f"# Daily Brief — {today}\n\n"
            "*No brief generated yet for today.*\n\n"
            f"*This file is auto-synced from `briefings/{today}.md` when available.*\n"
        )
        _write(dst, placeholder)
        print(f"[{_now()}] ℹ daily-brief.md placeholder written (no briefing found for {today})")


# ── MAIN SYNC LOOP ────────────────────────────────────────────────────────────

def run_sync():
    """Run all sync functions once."""
    print(f"\n[{_now()}] 🔄 Running vault sync...")
    try:
        sync_crm_snapshot()
    except Exception as e:
        print(f"  ERROR sync_crm_snapshot: {e}")
    try:
        sync_activity_log()
    except Exception as e:
        print(f"  ERROR sync_activity_log: {e}")
    try:
        sync_pending_actions()
    except Exception as e:
        print(f"  ERROR sync_pending_actions: {e}")
    try:
        sync_daily_brief()
    except Exception as e:
        print(f"  ERROR sync_daily_brief: {e}")
    print(f"[{_now()}] ✅ Vault sync complete.")


def main():
    watch_mode = "--watch" in sys.argv

    if watch_mode:
        print(f"[{_now()}] 🚀 Vault sync daemon started (every {INTERVAL_SECONDS}s)")
        print(f"   Vault: {VAULT_DIR}")
        print(f"   Bridge: {BRIDGE_DIR}")
        print("   Press Ctrl+C to stop.\n")
        while True:
            run_sync()
            time.sleep(INTERVAL_SECONDS)
    else:
        run_sync()


if __name__ == "__main__":
    main()
